### ISSUE TITLE
"Error!" when converting single mp3 with .cue file

### ISSUE THREAD

**Issue by zanhecht** [yermak/AudioBookConverter#266]
I'm trying to convert a single large .mp3 file with chapters in a .cue file. When I try to run it, I just get a status of "Error!" right away. I had had this issue with some other files, and was able to fix it by removing the periods from the narrator's name (R.C. Bray), but that didn't work with this file. My log is below:

```
23-06-2021 12:39:32 INFO  ConverterApplication:382 - Initialising application
23-06-2021 12:39:39 INFO  FFMediaLoader:382 - Loading media info
23-06-2021 12:39:39 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -version
23-06-2021 12:39:40 INFO  RunProcessFunction:386 - app/external/ffprobe.exe -v quiet -print_format json -show_error -show_format -show_streams -show_chapters C:\Users\ahecht\Music\AudioBooks\Jeremy Robinson\Infinite 2\Jeremy Robinson  Infinite 2.mp3
23-06-2021 12:39:41 INFO  FFMediaLoader:386 - Created AudioBookInfo AudioBookInfo[title=Infinite 2, writer=Jeremy Robinson, narrator=R C Bray, series=Infinite 2, genre=Audiobook, year=, bookNumber=0, totalTracks=0, comment=, tracks=[uk.yermak.audiobookconverter.Track@766df8b9, uk.yermak.audiobookconverter.Track@5cf43e73, uk.yermak.audiobookconverter.Track@fa43836, uk.yermak.audiobookconverter.Track@57969ef8, uk.yermak.audiobookconverter.Track@4ea71c83, uk.yermak.audiobookconverter.Track@335db482, uk.yermak.audiobookconverter.Track@1d164f57, uk.yermak.audiobookconverter.Track@7e146353, uk.yermak.audiobookconverter.Track@8213b16, uk.yermak.audiobookconverter.Track@56867734, uk.yermak.audiobookconverter.Track@79c5f644, uk.yermak.audiobookconverter.Track@24961cd4, uk.yermak.audiobookconverter.Track@25ee7adb, uk.yermak.audiobookconverter.Track@40349685, uk.yermak.audiobookconverter.Track@16952f11, uk.yermak.audiobookconverter.Track@2f1e1ab, uk.yermak.audiobookconverter.Track@549f7b8c, uk.yermak.audiobookconverter.Track@307b4f24, uk.yermak.audiobookconverter.Track@f29039d, uk.yermak.audiobookconverter.Track@258576a, uk.yermak.audiobookconverter.Track@2db40fb6, uk.yermak.audiobookconverter.Track@475c774b, uk.yermak.audiobookconverter.Track@aea1d6, uk.yermak.audiobookconverter.Track@408d55ae, uk.yermak.audiobookconverter.Track@4d492bb6, uk.yermak.audiobookconverter.Track@690beb7b, uk.yermak.audiobookconverter.Track@1c5e479d, uk.yermak.audiobookconverter.Track@3654419d, uk.yermak.audiobookconverter.Track@3244c87a, uk.yermak.audiobookconverter.Track@4a2ad7a, uk.yermak.audiobookconverter.Track@6a2e70dc, uk.yermak.audiobookconverter.Track@7ee28cad, uk.yermak.audiobookconverter.Track@6af18c13, uk.yermak.audiobookconverter.Track@7ba9254a, uk.yermak.audiobookconverter.Track@62181273, uk.yermak.audiobookconverter.Track@8757d79, uk.yermak.audiobookconverter.Track@6e82e970, uk.yermak.audiobookconverter.Track@5c33029f, uk.yermak.audiobookconverter.Track@7e1a18e0, uk.yermak.audiobookconverter.Track@5da73cef, uk.yermak.audiobookconverter.Track@24979742, uk.yermak.audiobookconverter.Track@60f45eb5, uk.yermak.audiobookconverter.Track@4e878753, uk.yermak.audiobookconverter.Track@2aa38a28, uk.yermak.audiobookconverter.Track@329625b9, uk.yermak.audiobookconverter.Track@70d5d4a8, uk.yermak.audiobookconverter.Track@21a78fe, uk.yermak.audiobookconverter.Track@34de405f, uk.yermak.audiobookconverter.Track@37e61090, uk.yermak.audiobookconverter.Track@6948e250, uk.yermak.audiobookconverter.Track@3844ba0f, uk.yermak.audiobookconverter.Track@7e5ec9e0, uk.yermak.audiobookconverter.Track@79bb342b, uk.yermak.audiobookconverter.Track@57cf132e, uk.yermak.audiobookconverter.Track@4ac65f1a, uk.yermak.audiobookconverter.Track@425f8e6b, uk.yermak.audiobookconverter.Track@6265e067, uk.yermak.audiobookconverter.Track@4d9cc966, uk.yermak.audiobookconverter.Track@35da7140, uk.yermak.audiobookconverter.Track@bc88d46, uk.yermak.audiobookconverter.Track@46633280, uk.yermak.audiobookconverter.Track@6d1f04d3, uk.yermak.audiobookconverter.Track@ba92841, uk.yermak.audiobookconverter.Track@444426cf]]
23-06-2021 12:39:43 ERROR FFMediaLoader:386 - ArtWork Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mp3, from 'C:\Users\ahecht\Music\AudioBooks\Jeremy Robinson\Infinite 2\Jeremy Robinson – Infinite 2.mp3':
  Metadata:
                    : major_brand
    title           : Infinite 2
    album_artist    : Jeremy Robinson
    album           : Infinite 2
    genre           : Audiobook
    copyright       : ©2021 Jeremy Robinson (P)2021 Jeremy Robinson
    encoder         : Lavf58.20.100
    encoded_by      : Lavf58.20.100
    HANDLER_NAME    : ANDLER_NAME
    comment         : 
    composer        : R C Bray
    artist          : Jeremy Robinson
    date            : 2021
  Duration: 10:34:59.33, start: 0.025056, bitrate: 128 kb/s
    Chapter #0:0: start 0.000000, end 30.790000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 30.790000, end 62.067000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 62.067000, end 105.906000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 105.906000, end 936.484000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 936.484000, end 1749.113000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 1749.113000, end 2524.799000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 2524.799000, end 3199.640000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 3199.640000, end 3821.679000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 3821.679000, end 4568.480000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 4568.480000, end 5506.844000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 5506.844000, end 6206.322000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 6206.322000, end 6839.948000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 6839.948000, end 7583.033000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 7583.033000, end 8241.412000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 8241.412000, end 8927.422000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 8927.422000, end 9514.887000
    Metadata:
      title           : Chapter 16
    Chapter #0:16: start 9514.887000, end 10100.286000
    Metadata:
      title           : Chapter 17
    Chapter #0:17: start 10100.286000, end 10664.159000
    Metadata:
      title           : Chapter 18
    Chapter #0:18: start 10664.159000, end 11359.527000
    Metadata:
      title           : Chapter 19
    Chapter #0:19: start 11359.527000, end 12085.034000
    Metadata:
      title           : Chapter 20
    Chapter #0:20: start 12085.034000, end 12445.919000
    Metadata:
      title           : Chapter 21
    Chapter #0:21: start 12445.919000, end 13205.745000
    Metadata:
      title           : Chapter 22
    Chapter #0:22: start 13205.745000, end 13776.933000
    Metadata:
      title           : Chapter 23
    Chapter #0:23: start 13776.933000, end 14421.449000
    Metadata:
      title           : Chapter 24
    Chapter #0:24: start 14421.449000, end 15053.543000
    Metadata:
      title           : Chapter 25
    Chapter #0:25: start 15053.543000, end 15689.166000
    Metadata:
      title           : Chapter 26
    Chapter #0:26: start 15689.166000, end 16264.301000
    Metadata:
      title           : Chapter 27
    Chapter #0:27: start 16264.301000, end 16927.184000
    Metadata:
      title           : Chapter 28
    Chapter #0:28: start 16927.184000, end 17594.897000
    Metadata:
      title           : Chapter 29
    Chapter #0:29: start 17594.897000, end 18201.774000
    Metadata:
      title           : Chapter 30
    Chapter #0:30: start 18201.774000, end 18876.987000
    Metadata:
      title           : Chapter 31
    Chapter #0:31: start 18876.987000, end 19565.505000
    Metadata:
      title           : Chapter 32
    Chapter #0:32: start 19565.505000, end 20180.021000
    Metadata:
      title           : Chapter 33
    Chapter #0:33: start 20180.021000, end 20758.872000
    Metadata:
      title           : Chapter 34
    Chapter #0:34: start 20758.872000, end 21407.544000
    Metadata:
      title           : Chapter 35
    Chapter #0:35: start 21407.544000, end 22066.434000
    Metadata:
      title           : Chapter 36
    Chapter #0:36: start 22066.434000, end 22585.725000
    Metadata:
      title           : Chapter 37
    Chapter #0:37: start 22585.725000, end 23274.661000
    Metadata:
      title           : Chapter 38
    Chapter #0:38: start 23274.661000, end 24032.816000
    Metadata:
      title           : Chapter 39
    Chapter #0:39: start 24032.816000, end 24571.611000
    Metadata:
      title           : Chapter 40
    Chapter #0:40: start 24571.611000, end 25113.078000
    Metadata:
      title           : Chapter 41
    Chapter #0:41: start 25113.078000, end 25752.276000
    Metadata:
      title           : Chapter 42
    Chapter #0:42: start 25752.276000, end 26325.670000
    Metadata:
      title           : Chapter 43
    Chapter #0:43: start 26325.670000, end 26998.747000
    Metadata:
      title           : Chapter 44
    Chapter #0:44: start 26998.747000, end 27610.059000
    Metadata:
      title           : Chapter 45
    Chapter #0:45: start 27610.059000, end 28273.360000
    Metadata:
      title           : Chapter 46
    Chapter #0:46: start 28273.360000, end 28794.787000
    Metadata:
      title           : Chapter 47
    Chapter #0:47: start 28794.787000, end 29416.873000
    Metadata:
      title           : Chapter 48
    Chapter #0:48: start 29416.873000, end 29886.218000
    Metadata:
      title           : Chapter 49
    Chapter #0:49: start 29886.218000, end 30519.101000
    Metadata:
      title           : Chapter 50
    Chapter #0:50: start 30519.101000, end 31114.995000
    Metadata:
      title           : Chapter 51
    Chapter #0:51: start 31114.995000, end 31713.326000
    Metadata:
      title           : Chapter 52
    Chapter #0:52: start 31713.326000, end 32263.059000
    Metadata:
      title           : Chapter 53
    Chapter #0:53: start 32263.059000, end 32792.079000
    Metadata:
      title           : Chapter 54
    Chapter #0:54: start 32792.079000, end 33418.344000
    Metadata:
      title           : Chapter 55
    Chapter #0:55: start 33418.344000, end 33961.297000
    Metadata:
      title           : Chapter 56
    Chapter #0:56: start 33961.297000, end 34560.116000
    Metadata:
      title           : Chapter 57
    Chapter #0:57: start 34560.116000, end 35103.626000
    Metadata:
      title           : Chapter 58
    Chapter #0:58: start 35103.626000, end 35784.992000
    Metadata:
      title           : Chapter 59
    Chapter #0:59: start 35784.992000, end 36457.628000
    Metadata:
      title           : Chapter 60
    Chapter #0:60: start 36457.628000, end 37378.392000
    Metadata:
      title           : Chapter 61
    Chapter #0:61: start 37378.392000, end 37719.980000
    Metadata:
      title           : Chapter 62
    Chapter #0:62: start 37719.980000, end 37957.822000
    Metadata:
      title           : Chapter 63
    Chapter #0:63: start 37957.822000, end 38099.290000
    Metadata:
      title           : Chapter 64
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.35
    Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 2400x2400 [SAR 72:72 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other
Stream mapping:
  Stream #0:1 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[image2 @ 0000019675fe6140] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
Output #0, image2, to 'C:\Users\ahecht\AppData\Local\Temp\~ABC_AudioBookConverter-5.5.18_-2029711340_-2029711340.jpg':
  Metadata:
                    : major_brand
    title           : Infinite 2
    album_artist    : Jeremy Robinson
    album           : Infinite 2
    genre           : Audiobook
    copyright       : ©2021 Jeremy Robinson (P)2021 Jeremy Robinson
    date            : 2021
    encoded_by      : Lavf58.20.100
    HANDLER_NAME    : ANDLER_NAME
    comment         : 
    composer        : R C Bray
    artist          : Jeremy Robinson
    encoder         : Lavf58.45.100
    Chapter #0:0: start 0.000000, end 30.765000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 30.765000, end 62.042000
    Metadata:
      title           : Chapter 2
    Chapter #0:2: start 62.042000, end 105.881000
    Metadata:
      title           : Chapter 3
    Chapter #0:3: start 105.881000, end 936.459000
    Metadata:
      title           : Chapter 4
    Chapter #0:4: start 936.459000, end 1749.088000
    Metadata:
      title           : Chapter 5
    Chapter #0:5: start 1749.088000, end 2524.774000
    Metadata:
      title           : Chapter 6
    Chapter #0:6: start 2524.774000, end 3199.615000
    Metadata:
      title           : Chapter 7
    Chapter #0:7: start 3199.615000, end 3821.654000
    Metadata:
      title           : Chapter 8
    Chapter #0:8: start 3821.654000, end 4568.455000
    Metadata:
      title           : Chapter 9
    Chapter #0:9: start 4568.455000, end 5506.819000
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 5506.819000, end 6206.297000
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 6206.297000, end 6839.923000
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 6839.923000, end 7583.008000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 7583.008000, end 8241.387000
    Metadata:
      title           : Chapter 14
    Chapter #0:14: start 8241.387000, end 8927.397000
    Metadata:
      title           : Chapter 15
    Chapter #0:15: start 8927.397000, end 9514.862000
    Metadata:
      title           : Chapter 16
    Chapter #0:16: start 9514.862000, end 10100.261000
    Metadata:
      title           : Chapter 17
    Chapter #0:17: start 10100.261000, end 10664.134000
    Metadata:
      title           : Chapter 18
    Chapter #0:18: start 10664.134000, end 11359.502000
    Metadata:
      title           : Chapter 19
    Chapter #0:19: start 11359.502000, end 12085.009000
    Metadata:
      title           : Chapter 20
    Chapter #0:20: start 12085.009000, end 12445.894000
    Metadata:
      title           : Chapter 21
    Chapter #0:21: start 12445.894000, end 13205.720000
    Metadata:
      title           : Chapter 22
    Chapter #0:22: start 13205.720000, end 13776.908000
    Metadata:
      title           : Chapter 23
    Chapter #0:23: start 13776.908000, end 14421.424000
    Metadata:
      title           : Chapter 24
    Chapter #0:24: start 14421.424000, end 15053.518000
    Metadata:
      title           : Chapter 25
    Chapter #0:25: start 15053.518000, end 15689.141000
    Metadata:
      title           : Chapter 26
    Chapter #0:26: start 15689.141000, end 16264.276000
    Metadata:
      title           : Chapter 27
    Chapter #0:27: start 16264.276000, end 16927.159000
    Metadata:
      title           : Chapter 28
    Chapter #0:28: start 16927.159000, end 17594.872000
    Metadata:
      title           : Chapter 29
    Chapter #0:29: start 17594.872000, end 18201.749000
    Metadata:
      title           : Chapter 30
    Chapter #0:30: start 18201.749000, end 18876.962000
    Metadata:
      title           : Chapter 31
    Chapter #0:31: start 18876.962000, end 19565.480000
    Metadata:
      title           : Chapter 32
    Chapter #0:32: start 19565.480000, end 20179.996000
    Metadata:
      title           : Chapter 33
    Chapter #0:33: start 20179.996000, end 20758.847000
    Metadata:
      title           : Chapter 34
    Chapter #0:34: start 20758.847000, end 21407.519000
    Metadata:
      title           : Chapter 35
    Chapter #0:35: start 21407.519000, end 22066.409000
    Metadata:
      title           : Chapter 36
    Chapter #0:36: start 22066.409000, end 22585.700000
    Metadata:
      title           : Chapter 37
    Chapter #0:37: start 22585.700000, end 23274.636000
    Metadata:
      title           : Chapter 38
    Chapter #0:38: start 23274.636000, end 24032.791000
    Metadata:
      title           : Chapter 39
    Chapter #0:39: start 24032.791000, end 24571.586000
    Metadata:
      title           : Chapter 40
    Chapter #0:40: start 24571.586000, end 25113.053000
    Metadata:
      title           : Chapter 41
    Chapter #0:41: start 25113.053000, end 25752.251000
    Metadata:
      title           : Chapter 42
    Chapter #0:42: start 25752.251000, end 26325.645000
    Metadata:
      title           : Chapter 43
    Chapter #0:43: start 26325.645000, end 26998.722000
    Metadata:
      title           : Chapter 44
    Chapter #0:44: start 26998.722000, end 27610.034000
    Metadata:
      title           : Chapter 45
    Chapter #0:45: start 27610.034000, end 28273.335000
    Metadata:
      title           : Chapter 46
    Chapter #0:46: start 28273.335000, end 28794.762000
    Metadata:
      title           : Chapter 47
    Chapter #0:47: start 28794.762000, end 29416.848000
    Metadata:
      title           : Chapter 48
    Chapter #0:48: start 29416.848000, end 29886.193000
    Metadata:
      title           : Chapter 49
    Chapter #0:49: start 29886.193000, end 30519.076000
    Metadata:
      title           : Chapter 50
    Chapter #0:50: start 30519.076000, end 31114.970000
    Metadata:
      title           : Chapter 51
    Chapter #0:51: start 31114.970000, end 31713.301000
    Metadata:
      title           : Chapter 52
    Chapter #0:52: start 31713.301000, end 32263.034000
    Metadata:
      title           : Chapter 53
    Chapter #0:53: start 32263.034000, end 32792.054000
    Metadata:
      title           : Chapter 54
    Chapter #0:54: start 32792.054000, end 33418.319000
    Metadata:
      title           : Chapter 55
    Chapter #0:55: start 33418.319000, end 33961.272000
    Metadata:
      title           : Chapter 56
    Chapter #0:56: start 33961.272000, end 34560.091000
    Metadata:
      title           : Chapter 57
    Chapter #0:57: start 34560.091000, end 35103.601000
    Metadata:
      title           : Chapter 58
    Chapter #0:58: start 35103.601000, end 35784.967000
    Metadata:
      title           : Chapter 59
    Chapter #0:59: start 35784.967000, end 36457.603000
    Metadata:
      title           : Chapter 60
    Chapter #0:60: start 36457.603000, end 37378.367000
    Metadata:
      title           : Chapter 61
    Chapter #0:61: start 37378.367000, end 37719.955000
    Metadata:
      title           : Chapter 62
    Chapter #0:62: start 37719.955000, end 37957.797000
    Metadata:
      title           : Chapter 63
    Chapter #0:63: start 37957.797000, end 38099.265000
    Metadata:
      title           : Chapter 64
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 2400x2400 [SAR 72:72 DAR 1:1], q=2-31, 200 kb/s, 90k fps, 90k tbn, 90k tbc (attached pic)
    Metadata:
      comment         : Other
      encoder         : Lavc58.91.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.8 q=10.0 size=N/A time=00:00:00.00 bitrate=N/A speed=8.34e-06x    
frame=    1 fps=0.8 q=10.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=8.34e-06x    
video:178kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

23-06-2021 12:39:54 ERROR FFMpegConcatenator:386 - Concat Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\ahecht\AppData\Local\Temp\filelist.1623064040561.txt: Invalid data found when processing input

23-06-2021 12:39:54 ERROR FFMpegConcatenator:382 - Error during concatination of files:
uk.yermak.audiobookconverter.ConversionException: Concatenation exit code 1!=0
	at uk.yermak.audiobookconverter.FFMpegConcatenator.concat(FFMpegConcatenator.java:74)
	at uk.yermak.audiobookconverter.ConversionJob.run(ConversionJob.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\ahecht\AppData\Local\Temp\filelist.1623064040561.txt: Invalid data found when processing input

	... 5 more
23-06-2021 12:39:54 ERROR ConversionJob:382 - Error during parallel conversion
java.lang.RuntimeException: uk.yermak.audiobookconverter.ConversionException: Concatenation exit code 1!=0
	at uk.yermak.audiobookconverter.FFMpegConcatenator.concat(FFMpegConcatenator.java:82)
	at uk.yermak.audiobookconverter.ConversionJob.run(ConversionJob.java:84)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: uk.yermak.audiobookconverter.ConversionException: Concatenation exit code 1!=0
	at uk.yermak.audiobookconverter.FFMpegConcatenator.concat(FFMpegConcatenator.java:74)
	... 4 more
Caused by: java.lang.Error: ffmpeg version 4.3.1-2021-01-01-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\ahecht\AppData\Local\Temp\filelist.1623064040561.txt: Invalid data found when processing input

	... 5 more
23-06-2021 12:40:00 INFO  ConverterApplication:382 - Closing application
```

**Comment by yermak** [comment]
@zanhecht ,

1) The program does not look for .cue file when source is mp3.
2) The program looks for .cure only for flac files.
3) Based on logs you provided i believe your mp3 files already has chapters embaded in it. Or something strange is happening here. So you don't need a cue. I strongly believe the program ignores it.
4) I never tested mp3 with chapters embeded in it as part of meta information. (btw, There was request in tracker to support output of mp3 with chapters - but this not widely used - so, it's not on roadmap.)

Unfortunately it's hard to tell what went wrong here - see point 4.
The best solution - upload file into cloud storage and share link with me at my_nikname @ gmail.com


P.S. As for cue I have explisit code 
```
if (FilenameUtils.getExtension(filename).equalsIgnoreCase("FLAC")) {
                    parseCueChapters(mediaInfo);
}
```

**Comment by whitleyphoto** [comment]
Not sure if protocol is to start a new post but I am getting the same Error! when trying to convert multiple mp3s.  I also attempted reconverting an m4b and got the same Error! result.  Thanks!

**Comment by zanhecht** [comment]
Thanks for the quick reply! VLC doesn't recognize any chapters in the mp3, but I'm not sure it even supports those in the first place. I've emailed you a link to the file.

**Comment by zanhecht** [comment]
I did some more debugging, and the problem only occurs if I click on the "Chapters" button before clicking "Start". If I directly click "Start" after adding the file, it works.

**Comment by yermak** [comment]
I close the bug as I could not reproduce it.
Hopefully issue will not appear in new version
