### ISSUE TITLE
macOS 12.2 Application is damaged and can't be opened 

### ISSUE THREAD

**Issue by dmuiX** [yermak/AudioBookConverter#374]
I think it would be a nice application to use. But unfortunately its not working and your instructions do not help.

**Comment by benglim** [comment]
Do this:

Use the command: sudo xattr -r -d com.apple.quarantine  put a space and drag the corrupted program or image (.dmg) into the Terminal window. Then restart the program.

**Comment by dmuiX** [comment]
Thanks. You're right its opening, but you can't do anything with it, so its still pointless to use it^^.
Maybe the dev wants to earn money with it, so he is not caring about the version released here/in github for free? If this is the case, just delete the release here. With the current state its pointless to use it.

**Comment by yermak** [comment]
@dmuiX, 
Thank you for your feedback. I'm considering such option - to remove build from here. However, i believe it works for some people.
To build product for Apple which works out of the box requires buying annual licence from Apple (as well as enormous amount of pointless efforts). That's why apple signed build is distributed on steam only (still can't make it work in Apple Store after days of efforts). 
I believe there are plenty alternatives on the market.

**Comment by yermak** [comment]
> Unfortunately the app can run, but cannot add files/folder. The finder dialogue box does not open.

Did you try drag and drop files from another finder window?

**Comment by dmuiX** [comment]
> > Unfortunately the app can run, but cannot add files/folder. The finder dialogue box does not open.
> 
> Did you try drag and drop files from another finder window?

Yes.

> @dmuiX, Thank you for your feedback. I'm considering such option - to remove build from here. However, i believe it works for some people. To build product for Apple which works out of the box requires buying annual licence from Apple (as well as enormous amount of pointless efforts). That's why apple signed build is distributed on steam only (still can't make it work in Apple Store after days of efforts). I believe there are plenty alternatives on the market.

Yes thats corrects. I am using much software that is unsigned and none of them throws this error. You just have to accept it at the privacy/security page and then it runs. So there must be something wrong with it.

**Comment by tamaracks** [comment]
I agree it seems that it can't just be the security certificate that's the problem. And yes, there are a few alternatives, but I was checking this one out because a post on Reddit said that they were able to edit chapter info on an existing m4b with this tool, and that isn't something I've found in other Mac tools. m4b-tool can, but I was hoping to find a GUI method and/or possibly something that can edit some of the audiobook-specific tags on an m4b. I have yet to find any tool for that.

As @dmuiX said, it's understandable, I just wanted to express what I was hoping to find here that isn't met elsewhere.

I tried to follow the directions about Mac where it says to cd into the app then run the executable inside the app package from Terminal, but that also gave me a message about it being damaged. The xattr command above, but as noted, you can't open any files to use it.

I did try running it from Terminal again after the xattr command, and it shows log messages in the Terminal while running. When I went to the File > Open menu in the GUI, the Terminal showed a whole bunch of exceptions and such. I don't know if they would be of any assistance, but I've attached them in a text file here in case it helps.

[audiobookconverterlog.txt](https://github.com/yermak/AudioBookConverter/files/8187141/audiobookconverterlog.txt)

**Comment by red-ochre** [comment]
@tamaracks> "said that they were able to edit chapter info on an existing m4b with this tool, and that isn't something I've found in other Mac tools. "

On a Mac running Monterey: After joining my m4a files into an m4b using ABC, I use Subler to edit the metadata and artwork and it also allows add, remove and edit of chapters. Works well for me.

**Comment by tamaracks** [comment]
> On a Mac running Monterey, I use Subler (subler dot org) to edit m4b metadata and artwork and it also allows add, remove and edit of chapters. Works well for me.

I've downloaded Subler, but it doesn't show me any of the existing tracks in an M4B file. Or I don't know how. Do you see chapter info for M4B's that already have them when you open them in Subler?

**Comment by dmuiX** [comment]
Interesting. For me not every Audiobook is working. I've found some that show the chapters correctly and some where there is nothing. Can't tell for sure which one works.

**Comment by dmuiX** [comment]
<img width="691" alt="Screenshot 2022-03-18 at 03 24 46" src="https://user-images.githubusercontent.com/19862760/158925511-258243b1-1198-4715-a343-048db2f5c6b6.png">

<img width="697" alt="Screenshot 2022-03-18 at 03 25 07" src="https://user-images.githubusercontent.com/19862760/158925554-2f0763ed-5dcc-40d9-aa82-8db697ad8d20.png">

**Comment by dmuiX** [comment]
<img width="694" alt="Screenshot 2022-03-18 at 03 25 40" src="https://user-images.githubusercontent.com/19862760/158925623-02286c05-55dd-4f92-8122-a7c081242482.png">

**Comment by red-ochre** [comment]
@tamaracks 
> I've downloaded Subler, but it doesn't show me any of the existing tracks in an M4B file. Or I don't know how. Do you see chapter info for M4B's that already have them when you open them in Subler?

As shown in the screenshots from @dmuiX above:
The first screen shows what you see if there are no chapters set. In the "Name" col, you see only "Metadata" and "Sound Track". If you want to add chapters, click on Edit → Insert a Chapter. You will then see what's on the second screen where a new item named "Text Track" has been added and that is where you can add, remove or edit chapters. If the m4b already had chapters, it will show them there, under "Text Track".

**Comment by dmuiX** [comment]
Well my experience is different: For some audiobooks sublet is not showing the chapters although they are integrated. So it's very reliable I would say

**Comment by tamaracks** [comment]
@red-ochre Thanks, I did find them now. I don't know if I just hadn't looked in the right spot before or if, as @dmuiX notes, some files didn't show it even if they had chapters. I can't remember which files I had tried initially.

Now I only wish I had a tool that would let me see the chapters and play from them at the same time to make it easier to verify the chapter marks.

**Comment by red-ochre** [comment]
> Well my experience is different: For some audiobooks sublet is not showing the chapters although they are integrated. So it's not very reliable I would say

I wonder if there may be more than one way to set "chapters" as I've always found mine in subler. Do Quicktime Player or VLC see the chapters in your audiobooks?

**Comment by red-ochre** [comment]
> Now I only wish I had a tool that would let me see the chapters and play from them at the same time to make it easier to verify the chapter marks.

I used to do this many years ago using "Chapter and Verse" but not any more -- it's very old now, unsupported and only runs on Win. I haven't found a good replacement yet but fingers crossed that @yermak AudioBookConverter will be the one. I'm very hopeful.

**Comment by dmuiX** [comment]
> > Well my experience is different: For some audiobooks sublet is not showing the chapters although they are integrated. So it's not very reliable I would say
> 
> I wonder if there may be more than one way to set "chapters" as I've always found mine in subler. Do Quicktime Player or VLC see the chapters in your audiobooks?

Haven't checked it yet but I would say yes. On my android device with smart audiobook player it's working. I Will report when I have tested it.
Regarding different ways Could be. In former times I have used chapter and verse as well. Then an app called audiobook creator and now for some time ffmpeg resp. M4b-tool which uses ffmpeg in the background. But I think the other two also do use ffmpeg.

**Comment by joshstrange** [comment]
I just wanted to chime in here with my use-case and how I solved it as this thread helped point me in the right direction.

I wanted to break my audiobook in half because I was creating a playlist of a series of books and wanted to reorder them chronologically instead of publish order. Doing so meant 3 books in the series needed to be broken into 2 parts so I could put another book in the middle. For example Book 1 till timestamp XX:XX, Book 2, Book 1 starting from timestamp XX:XX till the end.

I used Subler to get the chapter positions but from what I could see you can't "delete" chapters. You can delete the markers but the audio is still there. So if I deleted all the chapters after 12 I would be left with a m4b that had the normal first 11 chapters and then "chapter 12" would be chapter 12 + the rest of the book (which is not what I wanted).

Turns out what I wanted was as simple as:

     ffmpeg -i Book\ Name.m4b -ss 00:00:00 -to 12:41:46 -c copy Book\ Name\ Part\ 1.m4b
     ffmpeg -i Book\ Name.m4b -ss 12:41:46 -c copy Book\ Name\ Part\ 2.m4b

Where "12:41:46" was the breakpoint I wanted. I used Subler to figure out where the chapter started and I had a wiki guide for the series that has something like "Stop 27 minutes and 12 seconds into chapter 12" so I added that time to the start of chapter 12 to get my cut timestamp. This worked like a charm and inspecting the resulting m4b shows part 1 has chapters 1-12 and part 2 has chapters 12-24 (Both parts have part of chapter 12 in them). The only thing that was "lost" was the album art for part 2. I assume it's stored at the start of the file or something but it was easy to fix, I just opened both parts in Subler, switched to the artwork tab, and drug the art from part 1 to part 2 and saved it (I also edited both names to have "Part X" so I could tell the difference in Plex).

You could do this without Subler (using ffprobe I think) but it was a nice sanity check with an easy to use GUI.

**Comment by estebanavv** [comment]
Installed using the instructions on Monterey 12.4 and executed as instructed[ Installation Manual](https://github.com/yermak/AudioBookConverter/wiki/Installation) in but cannot add any files. Error reported in console.

` AudiobookConverter.app ./Contents/MacOS/AudiobookConverter                                        
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Initialising application
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Exodus environment created: /Users/esteban/.abc/AudiobookConverter-6.1.1
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Exodus environment created: /Users/esteban/.abc/AudiobookConverter-6.1.1
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Exodus environment created: /Users/esteban/.abc/AudiobookConverter-6.1.1
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Exodus environment created: /Users/esteban/.abc/AudiobookConverter-6.1.1
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Exodus environment created: /Users/esteban/.abc/AudiobookConverter-6.1.1
 INFO [JavaFX Application Thread] (AbstractLogger.java:382) - Exodus environment created: /Users/esteban/.abc/AudiobookConverter-6.1.1
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1857)
	at javafx.fxml/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1724)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
	at javafx.controls/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1878)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:557)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:943)
	at javafx.graphics/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:77)
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.base/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1854)
	... 40 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.yermak.audiobookconverter.Platform
	at uk.yermak.audiobookconverter.fx.DialogHelper.selectFilesDialog(DialogHelper.java:55)
	at uk.yermak.audiobookconverter.fx.FilesController.selectFiles(FilesController.java:212)
	... 51 more
`

**Comment by yermak** [comment]
Duplicates #580
